"""Direct BIND9 zone-file management -- works without the agent.

This module provides:
* Zone file generation from DB records (BIND format)
* Writing zone files to /etc/bind/zones/ (Debian) or /var/named/ (RHEL)
* Reloading BIND via ``rndc reload``
* Removing zone files and cleaning up named.conf.local

All public helpers are plain ``async`` coroutines so they can be called from
the FastAPI request path.  Heavy I/O (file writes, subprocess) is offloaded
to the default executor via ``asyncio.to_thread`` / ``asyncio.create_subprocess_exec``.
"""

from __future__ import annotations

import asyncio
import datetime
import logging
import os
import re
import textwrap
from pathlib import Path
from typing import List, Optional, Sequence

from api.models.dns_records import DnsRecord

_log = logging.getLogger("hosthive.bind")

# ---------------------------------------------------------------------------
# Paths -- prefer Debian layout; fall back to RHEL/CentOS
# ---------------------------------------------------------------------------

_DEBIAN_ZONE_DIR = Path("/etc/bind/zones")
_RHEL_ZONE_DIR = Path("/var/named")
_NAMED_CONF_LOCAL = Path("/etc/bind/named.conf.local")

def _zone_dir() -> Path:
    """Return the directory where zone files should be written."""
    if _DEBIAN_ZONE_DIR.exists():
        return _DEBIAN_ZONE_DIR
    if _RHEL_ZONE_DIR.exists():
        return _RHEL_ZONE_DIR
    # Default to Debian location -- we'll create it if needed
    return _DEBIAN_ZONE_DIR


def _zone_file_path(zone_name: str) -> Path:
    """Return the full path for a zone's file (e.g. ``/etc/bind/zones/db.example.com``)."""
    safe_name = re.sub(r"[^a-zA-Z0-9._-]", "_", zone_name)
    return _zone_dir() / f"db.{safe_name}"


# ---------------------------------------------------------------------------
# SOA serial helper
# ---------------------------------------------------------------------------

def _serial() -> str:
    """Generate a SOA serial in YYYYMMDDnn format."""
    today = datetime.date.today().strftime("%Y%m%d")
    return f"{today}01"


# ---------------------------------------------------------------------------
# Zone file rendering
# ---------------------------------------------------------------------------

def generate_zone_file(
    zone_name: str,
    records: Sequence[DnsRecord],
    *,
    primary_ns: str = "ns1",
    admin_email: str = "admin",
    default_ttl: int = 3600,
    refresh: int = 3600,
    retry: int = 900,
    expire: int = 1209600,
    minimum: int = 86400,
) -> str:
    """Return a complete BIND zone file as a string.

    If no SOA or NS records exist in *records*, a default SOA and NS pair is
    injected so the zone is always valid.
    """
    fqdn = zone_name.rstrip(".") + "."
    ns_fqdn = f"{primary_ns}.{fqdn}" if "." not in primary_ns else primary_ns.rstrip(".") + "."
    admin_fqdn = f"{admin_email.replace('@', '.')}.{fqdn}" if "@" not in admin_email else admin_email.replace("@", ".") + "."
    # Ensure admin_fqdn ends with dot
    if not admin_fqdn.endswith("."):
        admin_fqdn += "."

    serial = _serial()

    has_soa = any(r.record_type == "SOA" for r in records)
    has_ns = any(r.record_type == "NS" for r in records)

    lines: list[str] = [
        f"; Zone file for {zone_name}",
        f"; Generated by NovaPanel BIND service",
        f"; {datetime.datetime.utcnow().isoformat()}Z",
        f"",
        f"$TTL {default_ttl}",
        f"$ORIGIN {fqdn}",
        f"",
    ]

    # Default SOA if none in DB
    if not has_soa:
        lines.append(textwrap.dedent(f"""\
            @\tIN\tSOA\t{ns_fqdn} {admin_fqdn} (
            \t\t\t{serial}\t; serial
            \t\t\t{refresh}\t\t; refresh
            \t\t\t{retry}\t\t; retry
            \t\t\t{expire}\t\t; expire
            \t\t\t{minimum}\t\t; minimum
            )"""))
        lines.append("")

    # Default NS if none in DB
    if not has_ns:
        lines.append(f"@\t{default_ttl}\tIN\tNS\t{ns_fqdn}")
        lines.append("")

    # User records
    for r in records:
        name_part = r.name if r.name else "@"
        ttl_part = str(r.ttl) if r.ttl else str(default_ttl)
        rtype = r.record_type.upper()

        # Value handling for different record types
        value = r.value
        if rtype in ("CNAME", "MX", "NS", "SRV", "PTR"):
            # FQDN values need trailing dot
            if value and not value.endswith("."):
                value = value + "."
        if rtype == "TXT":
            # Ensure TXT values are quoted
            if not value.startswith('"'):
                value = f'"{value}"'

        if r.priority is not None and rtype in ("MX", "SRV"):
            lines.append(f"{name_part}\t{ttl_part}\tIN\t{rtype}\t{r.priority}\t{value}")
        else:
            lines.append(f"{name_part}\t{ttl_part}\tIN\t{rtype}\t{value}")

    lines.append("")  # trailing newline
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Filesystem helpers (run in thread to avoid blocking)
# ---------------------------------------------------------------------------

def _write_zone_file_sync(zone_name: str, content: str) -> Path:
    """Write *content* to the zone file and return the path."""
    zdir = _zone_dir()
    zdir.mkdir(parents=True, exist_ok=True)
    path = _zone_file_path(zone_name)
    path.write_text(content, encoding="utf-8")
    _log.info("Wrote zone file %s (%d bytes)", path, len(content))
    return path


def _delete_zone_file_sync(zone_name: str) -> Optional[Path]:
    """Remove the zone file from disk. Returns the path if it existed."""
    path = _zone_file_path(zone_name)
    if path.exists():
        path.unlink()
        _log.info("Removed zone file %s", path)
        return path
    return None


def _ensure_named_conf_entry_sync(zone_name: str) -> None:
    """Add a ``zone`` stanza to ``named.conf.local`` if not already present.

    This is a best-effort helper for Debian BIND9 setups where zone declarations
    live in ``/etc/bind/named.conf.local``.
    """
    if not _NAMED_CONF_LOCAL.exists():
        _log.debug("named.conf.local not found at %s -- skipping", _NAMED_CONF_LOCAL)
        return

    fqdn = zone_name.rstrip(".")
    zone_file = str(_zone_file_path(zone_name))
    marker = f'zone "{fqdn}"'

    existing = _NAMED_CONF_LOCAL.read_text(encoding="utf-8")
    if marker in existing:
        _log.debug("Zone %s already declared in named.conf.local", fqdn)
        return

    stanza = textwrap.dedent(f"""\

        // managed by NovaPanel
        zone "{fqdn}" {{
            type master;
            file "{zone_file}";
            allow-transfer {{ none; }};
        }};
    """)
    with _NAMED_CONF_LOCAL.open("a", encoding="utf-8") as f:
        f.write(stanza)
    _log.info("Added zone stanza for %s to named.conf.local", fqdn)


def _remove_named_conf_entry_sync(zone_name: str) -> None:
    """Remove the ``zone`` stanza for *zone_name* from ``named.conf.local``."""
    if not _NAMED_CONF_LOCAL.exists():
        return

    fqdn = zone_name.rstrip(".")
    content = _NAMED_CONF_LOCAL.read_text(encoding="utf-8")

    # Match the stanza we generated (including the comment above it)
    pattern = re.compile(
        r"\n?// managed by NovaPanel\nzone \"%s\" \{[^}]*\};\n?" % re.escape(fqdn),
        re.DOTALL,
    )
    new_content, n = pattern.subn("", content)
    if n:
        _NAMED_CONF_LOCAL.write_text(new_content, encoding="utf-8")
        _log.info("Removed zone stanza for %s from named.conf.local", fqdn)


# ---------------------------------------------------------------------------
# rndc reload
# ---------------------------------------------------------------------------

async def _rndc_reload(zone_name: Optional[str] = None) -> tuple[bool, str]:
    """Execute ``rndc reload [zone]``.  Returns ``(success, output)``."""
    cmd: list[str] = ["rndc", "reload"]
    if zone_name:
        cmd.append(zone_name)

    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=15)
        output = (stdout or b"").decode() + (stderr or b"").decode()
        ok = proc.returncode == 0
        if ok:
            _log.info("rndc reload %s succeeded: %s", zone_name or "(all)", output.strip())
        else:
            _log.warning("rndc reload %s failed (rc=%d): %s", zone_name or "(all)", proc.returncode, output.strip())
        return ok, output.strip()
    except FileNotFoundError:
        msg = "rndc not found -- BIND9 may not be installed"
        _log.warning(msg)
        return False, msg
    except asyncio.TimeoutError:
        msg = "rndc reload timed out after 15s"
        _log.warning(msg)
        return False, msg
    except Exception as exc:
        msg = f"rndc reload error: {exc}"
        _log.warning(msg)
        return False, msg


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

async def write_zone(zone_name: str, records: Sequence[DnsRecord]) -> tuple[bool, str]:
    """Generate a zone file, write it to disk, update named.conf.local, and reload BIND.

    Returns ``(bind_ok, message)``.  Even if BIND reload fails the zone file
    is still on disk so a manual ``rndc reload`` will pick it up later.
    """
    content = generate_zone_file(zone_name, records)

    # File I/O in thread pool
    await asyncio.to_thread(_write_zone_file_sync, zone_name, content)
    await asyncio.to_thread(_ensure_named_conf_entry_sync, zone_name)

    ok, output = await _rndc_reload(zone_name)
    if ok:
        return True, f"Zone {zone_name} written and BIND reloaded."
    return False, f"Zone file written but BIND reload failed: {output}"


async def remove_zone(zone_name: str) -> tuple[bool, str]:
    """Remove a zone file, clean up named.conf.local, and reload BIND.

    Returns ``(bind_ok, message)``.
    """
    await asyncio.to_thread(_delete_zone_file_sync, zone_name)
    await asyncio.to_thread(_remove_named_conf_entry_sync, zone_name)

    ok, output = await _rndc_reload()
    if ok:
        return True, f"Zone {zone_name} removed and BIND reloaded."
    return False, f"Zone file removed but BIND reload failed: {output}"
