"""GeoIP-based geo-blocking service for the WAF.

Manages the nginx geoip2 map configuration at /etc/nginx/conf.d/geo-block.conf,
persists rules in a JSON state file, and provides helpers for checking GeoIP
module / database status.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
GEOIP_DB_PATH = Path("/usr/share/GeoIP/GeoLite2-Country.mmdb")
GEO_BLOCK_CONF = Path("/etc/nginx/conf.d/geo-block.conf")
GEO_STATE_FILE = Path("/etc/nginx/waf/geo-state.json")

# Default state
_DEFAULT_STATE: dict[str, Any] = {
    "mode": "blacklist",  # "blacklist" or "whitelist"
    "enabled": False,
    "rules": {},  # country_code -> action ("block" | "allow")
}


# ---------------------------------------------------------------------------
# Shell helper (mirrors nginx_service._run)
# ---------------------------------------------------------------------------
async def _run(cmd: str) -> tuple[int, str, str]:
    proc = await asyncio.create_subprocess_shell(
        cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()
    return proc.returncode, stdout.decode().strip(), stderr.decode().strip()


async def _nginx_test_and_reload() -> tuple[bool, str]:
    rc, out, err = await _run("nginx -t")
    if rc != 0:
        msg = f"nginx config test failed: {err or out}"
        logger.error(msg)
        return False, msg
    rc, out, err = await _run("systemctl reload nginx")
    if rc != 0:
        msg = f"nginx reload failed: {err or out}"
        logger.error(msg)
        return False, msg
    return True, "nginx reloaded successfully"


# ---------------------------------------------------------------------------
# Service
# ---------------------------------------------------------------------------
class GeoBlockingService:
    """Manage geo-blocking rules and generate the nginx config."""

    # -- state persistence ---------------------------------------------------

    @staticmethod
    def _read_state() -> dict[str, Any]:
        if GEO_STATE_FILE.exists():
            try:
                return json.loads(GEO_STATE_FILE.read_text())
            except (json.JSONDecodeError, OSError):
                logger.warning("Corrupt geo-state.json, resetting")
        return dict(_DEFAULT_STATE)

    @staticmethod
    def _write_state(state: dict[str, Any]) -> None:
        GEO_STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
        GEO_STATE_FILE.write_text(json.dumps(state, indent=2))

    # -- nginx config generation ---------------------------------------------

    @staticmethod
    def _render_nginx_conf(state: dict[str, Any]) -> str:
        """Render /etc/nginx/conf.d/geo-block.conf from current state."""
        mode = state.get("mode", "blacklist")
        rules: dict[str, str] = state.get("rules", {})

        lines = [
            "# Auto-generated by HostHive geo-blocking service",
            f"# Mode: {mode}",
            f"# Updated: {datetime.now(timezone.utc).isoformat()}Z",
            "",
            "geoip2 /usr/share/GeoIP/GeoLite2-Country.mmdb {",
            "    auto_reload 60m;",
            "    $geoip2_country_code country iso_code;",
            "}",
            "",
            "map $geoip2_country_code $geo_blocked {",
        ]

        if mode == "blacklist":
            # default = allow, listed countries = blocked
            lines.append("    default 0;")
            for cc, action in sorted(rules.items()):
                if action == "block":
                    lines.append(f"    {cc} 1;")
        else:
            # whitelist: default = blocked, listed countries = allowed
            lines.append("    default 1;")
            for cc, action in sorted(rules.items()):
                if action == "allow":
                    lines.append(f"    {cc} 0;")
            # Always allow empty (internal requests without GeoIP data)
            lines.append("    '' 0;")

        lines.extend(["}", ""])
        return "\n".join(lines)

    async def _write_and_reload(self, state: dict[str, Any]) -> tuple[bool, str]:
        """Persist state, write nginx conf, and reload."""
        self._write_state(state)

        if not state.get("enabled", False):
            # Remove the conf file so nginx does not load geoip2 block
            if GEO_BLOCK_CONF.exists():
                GEO_BLOCK_CONF.unlink()
            ok, msg = await _nginx_test_and_reload()
            return ok, msg

        conf_text = self._render_nginx_conf(state)
        GEO_BLOCK_CONF.parent.mkdir(parents=True, exist_ok=True)
        GEO_BLOCK_CONF.write_text(conf_text)
        ok, msg = await _nginx_test_and_reload()

        if not ok:
            # Rollback: remove broken config
            logger.error("Geo-block conf caused nginx failure, rolling back: %s", msg)
            GEO_BLOCK_CONF.unlink(missing_ok=True)
            await _nginx_test_and_reload()

        return ok, msg

    # -- public API ----------------------------------------------------------

    async def get_status(self) -> dict[str, Any]:
        """Return GeoIP installation and database status."""
        # Check libnginx-mod-http-geoip2
        rc, _, _ = await _run("dpkg -s libnginx-mod-http-geoip2 2>/dev/null")
        installed = rc == 0

        # Check geoipupdate
        rc2, _, _ = await _run("command -v geoipupdate")
        geoipupdate_installed = rc2 == 0

        db_exists = GEOIP_DB_PATH.exists()
        db_last_modified = None
        if db_exists:
            mtime = os.path.getmtime(GEOIP_DB_PATH)
            db_last_modified = datetime.fromtimestamp(mtime, tz=timezone.utc).isoformat()

        state = self._read_state()

        return {
            "installed": installed,
            "db_exists": db_exists,
            "db_path": str(GEOIP_DB_PATH),
            "db_last_modified": db_last_modified,
            "geoipupdate_installed": geoipupdate_installed,
            "enabled": state.get("enabled", False),
        }

    async def list_rules(self) -> dict[str, Any]:
        """Return current geo-blocking rules."""
        state = self._read_state()
        rules_list = [
            {"country_code": cc, "action": action}
            for cc, action in sorted(state.get("rules", {}).items())
        ]
        return {
            "mode": state.get("mode", "blacklist"),
            "rules": rules_list,
            "total": len(rules_list),
        }

    async def add_rule(self, country_code: str, action: str) -> dict[str, Any]:
        """Add or update a geo-blocking rule and regenerate config."""
        cc = country_code.upper().strip()
        if len(cc) != 2 or not cc.isalpha():
            raise ValueError(f"Invalid country code: {cc!r}")
        if action not in ("block", "allow"):
            raise ValueError(f"Invalid action: {action!r}")

        state = self._read_state()
        state["rules"][cc] = action
        # Auto-enable when first rule is added
        if not state.get("enabled"):
            state["enabled"] = True

        ok, msg = await self._write_and_reload(state)
        if not ok:
            raise RuntimeError(f"Failed to apply geo rule: {msg}")

        return await self.list_rules()

    async def remove_rule(self, country_code: str) -> dict[str, Any]:
        """Remove a geo-blocking rule."""
        cc = country_code.upper().strip()
        state = self._read_state()
        if cc not in state.get("rules", {}):
            raise ValueError(f"No rule for country code {cc!r}")

        del state["rules"][cc]
        # Auto-disable when no rules left
        if not state["rules"]:
            state["enabled"] = False

        ok, msg = await self._write_and_reload(state)
        if not ok:
            raise RuntimeError(f"Failed to remove geo rule: {msg}")

        return await self.list_rules()

    async def set_mode(self, mode: str) -> dict[str, Any]:
        """Set whitelist or blacklist mode."""
        if mode not in ("blacklist", "whitelist"):
            raise ValueError(f"Invalid mode: {mode!r}")

        state = self._read_state()
        state["mode"] = mode

        if state.get("enabled") and state.get("rules"):
            ok, msg = await self._write_and_reload(state)
            if not ok:
                raise RuntimeError(f"Failed to set geo mode: {msg}")
        else:
            self._write_state(state)

        return await self.list_rules()

    async def update_database(self) -> dict[str, Any]:
        """Run geoipupdate to refresh the MaxMind database."""
        rc, out, err = await _run("command -v geoipupdate")
        if rc != 0:
            return {"ok": False, "error": "geoipupdate is not installed"}

        rc, out, err = await _run("geoipupdate -v 2>&1")
        if rc != 0:
            return {"ok": False, "error": f"geoipupdate failed: {err or out}"}

        # Reload nginx to pick up the new database
        ok, msg = await _nginx_test_and_reload()
        return {
            "ok": True,
            "output": out,
            "nginx_reloaded": ok,
            "nginx_message": msg,
        }
